make goplugin importable from other go projects (#89)
Depends on https://github.com/tetratelabs/built-on-envoy/pull/88. I'll
rebase once that is merged and keep it as draft unitl then.

Renames the `extensions/internal` to `extensions/core` so that the
`goplugin` can be go-imported by users that want to build their own
libcomposer with a custom set of embedded plugins.

This has two additional changes:

* Renames the `build_local_cache` make target in libcomposer to
`install`, to align it better with other plugins and naming.
* Small refactor to `goplugin` to remove code repetition around version
and dependency checks.
* Better split CI workflows

---------

Signed-off-by: Ignasi Barrera <ignasi@tetrate.io>

diff --git a/extensions/core/goplugin/Makefile b/extensions/core/goplugin/Makefile
--- a/extensions/core/goplugin/Makefile
+++ b/extensions/core/goplugin/Makefile
@@ -8,7 +8,7 @@ SHELL    := /bin/bash
 repo_dir := $(shell git rev-parse --show-toplevel)
 
 .PHONY: all
-all: lint gen test
+all: lint gen test check
 
 .PHONY: lint
 lint:
@@ -32,3 +32,12 @@ test:
 clean:
 	@echo "Cleaning generated code..."
 	@rm -f *.pb.*
+
+.PHONY: check
+check:  ## Run all necessary steps to prepare for a commit and check for any differences in the codebase
+	@if [ ! -z "`git status -s`" ]; then \
+		echo "The following differences will fail CI until committed:"; \
+		git status; \
+		echo "Please ensure you have run 'make check' and committed the changes."; \
+		exit 1; \
+	fi
